"""initial

Revision ID: 765e5a082e76
Revises: 
Create Date: 2026-01-23 14:12:28.838400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '765e5a082e76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paperaccess',
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paperaccess_paper_id'), 'paperaccess', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paperaccess_role'), 'paperaccess', ['role'], unique=False)
    op.create_index(op.f('ix_paperaccess_session_id'), 'paperaccess', ['session_id'], unique=False)
    op.create_index(op.f('ix_paperaccess_subject_id'), 'paperaccess', ['subject_id'], unique=False)
    op.create_index(op.f('ix_paperaccess_subject_type'), 'paperaccess', ['subject_type'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_paperaccess_subject_type'), table_name='paperaccess')
    op.drop_index(op.f('ix_paperaccess_subject_id'), table_name='paperaccess')
    op.drop_index(op.f('ix_paperaccess_session_id'), table_name='paperaccess')
    op.drop_index(op.f('ix_paperaccess_role'), table_name='paperaccess')
    op.drop_index(op.f('ix_paperaccess_paper_id'), table_name='paperaccess')
    op.drop_table('paperaccess')
    # ### end Alembic commands ###
